inherit_from: .rubocop_todo.yml

require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.X
  Exclude:
    - db/**/*
    - script/**/*
    - bin/**/*
    - config/**/*
    - spec/**/*
    - vendor/bundle/**/*

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - app/admin/*
    - app/controllers/concerns/*

Metrics/MethodLength:
  Exclude:
    - app/helpers/*
    - app/models/ability.rb

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - config/initializer/*

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - app/helpers/*

Lint/MissingSuper:
  Enabled: false
Style/RedundantFetchBlock:
  Exclude:
    - app/forms/addresses_form.rb