inherit_from: .rubocop_todo.yml

require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - db/**/*
    - script/**/*
    - bin/**/*
    - config/**/*
Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - app/admin/*
    - app/controllers/concerns/*

Metrics/MethodLength:
  Exclude:
    - app/helpers/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - config/initializer/*

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - app/helpers/*

Lint/MissingSuper:
  Enabled: false
