version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: the offical
    docker:
      - image: circleci/ruby:3.0.1
      - image: postgres:14.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
          TZ: "Etc/UTC"
          RAILS_ENV: test
caches:
  - &bundle_cache_v1 v2_repo-{( checksum "Gemfile.lock" )}
  - &bundle_cache v2_repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_v1
            - *bundle_cache
      - run: bundle check --path=vendor/cache || bundle install --local --path=vendor/cache --jobs 4 --retry 3
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle
      - run:
          name: Database setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:structure:load
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          name: fasterer
          command: bundle exec fasterer
  run_specs:
    steps:
      - run:
          name: run specs
          command: bundle exec rspec --format progress
jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs
workflows:
  version: 2
  build:
    jobs:
      - lintering
      - run_specs

